name: Terraform Production Deployment
on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - terraform/production/**
  # pull_request:
  #   paths:
  #     - terraform/production/**
  workflow_dispatch:

jobs:
# Production Account Baseline
  call-production:
    uses: ./.github/workflows/tf-account.yml
    with:
      account: production
    secrets:
      AWS_MANAGEMENT_ACCOUNT: ${{ secrets.AWS_MANAGEMENT_ACCOUNT }}
    permissions:
      id-token: write
      issues: write
      contents: read